### ISSUE TITLE
[BUG] Graph does not display

### ISSUE THREAD

**Issue by Dahie** [444B/streamlit-analytics2#45]
**Describe the bug**
I integrated streamlit-analytics2 in my streamlit app, open the app in my browser with the parameter `analytics=on`, but the graphs are not displayed.

**To Reproduce**
You can use this boilerplate, to simulate: https://github.com/WhatAVenture/wav-streamlit-boilerplate
1. Run the app
2. Open http://localhost:8501?analytics=on
3. It opens the page, but without showing the analytics summary and timeline.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 123.0.1

**Additional context**
I have the same issue in a different project, but the boilerplate shows it clearest.

**Comment by 444B** [comment]
@Dahie thanks for raising the bug?

1. Can you confirm if your file that uses streamlit has the following:

```python
Import streamlit_analytics2 as streamlit_analytics
```

2. Did you install streamlit_analytics2 via pip? If you deployed somewhere, did you accordingly update your requirements.txt or pipfile?

3. Can you share errors or a screenshot of what is shown?

**Comment by Dahie** [comment]
1. yes, see: https://github.com/WhatAVenture/wav-streamlit-boilerplate/blob/a9866a99a899218a9ae24532db4f831f49d98a28/wav_streamlit_boilerplate/app.py#L3
2. kinda, I use poetry for dependency management, but it's correctly in the dependencies and it is tracking data: https://github.com/WhatAVenture/wav-streamlit-boilerplate/blob/a9866a99a899218a9ae24532db4f831f49d98a28/poetry.lock#L1875
3. I get no error and it just does not display, so there is nothing to screenshot.

**Comment by 444B** [comment]
Investigation notes:
- streamlit_analytics2 version 0.5.3 is being used in poetry.lock and pyproject.toml (latest). This did go through testing before package deploy [link](https://test.pypi.org/manage/project/streamlit-analytics2/release/0.5.3/)
- streamlit version 1.30 is being used in poetry.lock and pyproject.toml
- import streamlit_analytics2 as streamlit_analytics being used in app.py
- I noticed that streamlit is called with the following:
```python
    with streamlit_analytics.track(
        save_to_json=log_path,
        load_from_json=log_path):
        main()
```
I havent seen streamlit used in this manner with main and will test if it is supported. 

Next steps:
- currently replicating setup

**Comment by 444B** [comment]
Investigation notes2:
- turns out that calling with streamlit_analytics.track on your main () does work and is actually a smart way of doing it. I might just update the documentation with that example.
- I was able to get the analytics dashboard to appear on the wav-streamlit-boilerplate/app.py page. Screenshot at bottom
commands I ran to get this result:
- replicated environment using codespace
```sh
poetry build
poetry install
poetry show
poetry shell
streamlit run wav_streamlit_boilerplate/app.py 
```

![image](https://github.com/444B/streamlit-analytics2/assets/15311579/75cb3631-9809-42a9-813b-1ee0dfbc8f6e)

Next steps:
@Dahie  does this fit in with the way you might have been setting up the environment? I cant see anything wrong with your setup or dependencies. What are your thoughts? 
I can not find an issue with the way streamlit_analytics is being called or version 0.5.3

**Comment by Dahie** [comment]
This is how I set it up as well. Will also investigate further. Thanks!

**Comment by 444B** [comment]
Sure, no worries! Comment back here if you have any findings
ill close the issue later this week without further comments

**Comment by Dahie** [comment]
ok, I found my issue. I was using the wrong parameter value in my tests. `http://localhost:8501?analytics=true` instead of `on`

Sorry, of the inconvenience. 😅
